# Generated by Django 3.2.5 on 2021-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0002_listepresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='check_prise_parametre',
            field=models.BooleanField(default=False),
        ),
    ]
