# Generated by Django 3.2.5 on 2021-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0003_listepresence_check_prise_parametre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listepresence',
            name='a_paye',
        ),
        migrations.AddField(
            model_name='listepresence',
            name='nbre_quittances',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
