# Generated by Django 3.2.5 on 2021-08-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0004_auto_20210817_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listepresence',
            old_name='nbre_quittances',
            new_name='nbre_quittances_non_consommees',
        ),
    ]
