# Generated by Django 3.1.4 on 2021-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0005_rename_nbre_quittances_listepresence_nbre_quittances_non_consommees'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antecedent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnie',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='group_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(choices=[('Chrétien', 'Chrétien'), ('Musulman', 'Musulman'), ('Boudiste', 'Boudiste'), ('Athée', 'Athée')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listepresence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
