# Generated by Django 3.2.5 on 2021-08-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateau_technique', '0002_auto_20210829_1400'),
        ('secretariat', '0006_auto_20210828_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepresence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Internement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_internement', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(default=None, null=True)),
                ('lit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateau_technique.lit')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariat.patient')),
            ],
        ),
    ]
