# Generated by Django 3.2.5 on 2021-08-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0007_auto_20210829_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
