# Generated by Django 3.2.5 on 2021-08-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0008_listepresence_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listepresence',
            name='nbre_quittances_non_consommees',
        ),
    ]
