# Generated by Django 3.2.5 on 2021-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0010_rename_check_prise_parametre_listepresence_parametres_pris'),
    ]

    operations = [
        migrations.AddField(
            model_name='internement',
            name='en_cours',
            field=models.BooleanField(default=True),
        ),
    ]
