# Generated by Django 3.2.5 on 2021-09-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0013_alter_listepresence_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepresence',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariat.patient'),
        ),
    ]
