# Generated by Django 3.2.5 on 2022-06-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0014_alter_listepresence_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepresence',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariat.patient'),
        ),
    ]
