# Generated by Django 3.2.5 on 2022-06-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0015_alter_listepresence_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='colorpatient',
            field=models.BooleanField(default=False),
        ),
    ]
