# Generated by Django 3.2.5 on 2022-06-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0024_auto_20220610_0155'),
        ('secretariat', '0016_listepresence_colorpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='examens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.examen'),
        ),
    ]
