# Generated by Django 3.2.5 on 2022-06-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0028_alter_prescriptionexamen_type'),
        ('secretariat', '0017_listepresence_examens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepresence',
            name='examens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.prescriptionexamen'),
        ),
    ]
