# Generated by Django 3.2.5 on 2022-06-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0019_alter_listepresence_examens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listepresence',
            name='examens',
        ),
    ]
