# Generated by Django 3.2.5 on 2022-06-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0029_alter_prescriptionexamen_type'),
        ('secretariat', '0021_listepresence_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listepresence',
            name='prescription',
        ),
        migrations.AddField(
            model_name='listepresence',
            name='examens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.examen'),
        ),
    ]
