# Generated by Django 3.2.5 on 2022-06-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0030_alter_prescriptionexamen_type'),
        ('secretariat', '0022_auto_20220619_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listepresence',
            name='examens',
        ),
        migrations.AddField(
            model_name='listepresence',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.prescriptionexamen'),
        ),
    ]
