# Generated by Django 3.2.5 on 2022-01-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0019_personnel_should_update_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='service',
        ),
    ]
