# Generated by Django 3.2.5 on 2022-01-02 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0020_remove_poste_service'),
        ('consultation', '0014_prescriptionexamen_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenCovid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_prelevement', models.DateTimeField(auto_now=True)),
                ('type_prelevement', models.CharField(choices=[('Nasopharynge', 'Nasopharynge'), ('Autre', 'Autre')], default=('Nasopharynge', 'Nasopharynge'), max_length=30)),
                ('indication_du_prelevement', models.CharField(choices=[('Volontaire', 'Volontaire'), ('Controle', 'Controle'), ('Autre', 'Autre')], default=('Volontaire', 'Volontaire'), max_length=30)),
                ('resultat', models.CharField(choices=[('En attente', 'En attente'), ('Presence de SARS Cov Ag', 'Presence de SARS Cov Ag'), ('Absence de SARS Cov Ag', 'Absence de SARS Cov Ag'), ('Indetermine', 'Indetermine')], default=('En attente', 'En attente'), max_length=30)),
                ('Conclusion', models.CharField(max_length=200)),
                ('Conduite_a_tenir', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
                ('laborantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.laborantin')),
            ],
        ),
    ]
