# Generated by Django 3.2.5 on 2022-01-31 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0016_remove_examencovid_conduite_a_tenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='examencovid',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.prescriptionexamen'),
        ),
    ]
