# Generated by Django 3.2.5 on 2022-03-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0020_remove_poste_service'),
        ('consultation', '0017_examencovid_prescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamenCovid',
            new_name='BulletinExamen',
        ),
    ]
