# Generated by Django 3.2.5 on 2022-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_rename_examencovid_bulletinexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinexamen',
            name='qExam_Buy',
            field=models.BooleanField(default=False),
        ),
    ]
