# Generated by Django 3.2.5 on 2022-06-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_auto_20210901_1018'),
        ('consultation', '0019_bulletinexamen_qexam_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='caissier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caisse.quittance'),
        ),
    ]
