# Generated by Django 3.2.5 on 2022-06-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_auto_20210901_1018'),
        ('consultation', '0020_examen_caissier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='caissier',
        ),
        migrations.AddField(
            model_name='examen',
            name='quittqnce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.quittance'),
        ),
    ]
