# Generated by Django 3.2.5 on 2022-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0021_auto_20220601_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='quittqnce',
            new_name='quittance',
        ),
    ]
