# Generated by Django 3.2.5 on 2022-06-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_auto_20220602_0216'),
        ('consultation', '0022_rename_quittqnce_examen_quittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='quittance',
        ),
        migrations.AlterField(
            model_name='test',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.quittance'),
        ),
    ]
