# Generated by Django 3.2.5 on 2022-06-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0023_auto_20220602_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinexamen',
            name='indication_du_prelevement',
        ),
        migrations.RemoveField(
            model_name='bulletinexamen',
            name='type_prelevement',
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='achcv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='acideAscorbique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='acideUrique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='aghbs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='alat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='asat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='aslo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='basophile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='biluribine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='calcium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='chlamydiale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='chlore',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='cholesterolT',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='coprscetonique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='creatinine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='crp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='densite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='electroPhoreseHb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='eosinophiles',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='facteursRhumatoides',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='glecemieAjeun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='globuleBlanc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='globuleRouge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='glucose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='gouttesEpaisse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='groupeSanguin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='hcg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='hdglyque',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='hdlcholesterol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='hematocritie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='hpylori',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='lcr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='ldlcholesterol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='leucocytes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='lymphocytes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='magnesium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='monocytes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='mycoplasme',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='neutrophiles',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='nitrites',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='pal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='ph',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='plaquettes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='potassium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='proteine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='rmf',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='rubeole',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='sang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='selbilaires',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='selles',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='sniptest',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='soduim',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='tauxHemoglobines',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='tck',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='testEmmel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='toxoplasmose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='tp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='tpha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='triglycerides',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='uree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='urines',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='urobilinogene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='vdrl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='vgm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='vih',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='vs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulletinexamen',
            name='widalTest',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bulletinexamen',
            name='Conclusion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
