# Generated by Django 3.2.5 on 2022-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0024_auto_20220610_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='type',
            field=models.CharField(default='', max_length=80000),
        ),
    ]
