# Generated by Django 3.2.5 on 2022-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0025_alter_examen_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionexamen',
            name='label',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='label',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
