# Generated by Django 3.2.5 on 2022-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0030_alter_prescriptionexamen_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='type',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
