# Generated by Django 3.2.5 on 2022-06-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0020_remove_poste_service'),
        ('caisse', '0008_auto_20210901_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaps',
            name='laborantin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grh.laborantin'),
        ),
        migrations.AlterField(
            model_name='tiaps',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grh.medecin'),
        ),
    ]
